service: pickle-v2
frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-plugin-warmup

custom:
  stage: ${opt:stage, self:provider.stage}
  table:
    ASSET_DATA:
      brining: "brining-asset"
      prod: "asset"
    REWARD_DATA:
      brining: "brining-reward"
      prod: "reward"

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-west-1
  apiGateway:
    shouldStartNameWithService: true
  environment:
    PICKLE: "https://api.thegraph.com/subgraphs/name/axejintao/pickle"
    UNISWAP: "https://api.thegraph.com/subgraphs/name/uniswap/uniswap-v2"
    ASSET_DATA: ${self:custom.table.ASSET_DATA.${self:custom.stage}}
    REWARD_DATA: ${self:custom.table.REWARD_DATA.${self:custom.stage}}

functions:
  get-jar-data:
    handler: service/history/jar/handler.handler
    role: arn:aws:iam::135612478587:role/pickle-brining-us-west-1-lambdaRole
    timeout: 10
    events:
      - http:
          path: /jar/{jarname}
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                count: false

  get-jar-performance:
    handler: service/history/jar/performance/handler.handler
    role: arn:aws:iam::135612478587:role/pickle-brining-us-west-1-lambdaRole
    timeout: 10
    events:
      - http:
          path: /jar/{jarname}/performance
          method: get
          cors: true

  get-reward-data:
    handler: service/history/reward/handler.handler
    role: arn:aws:iam::135612478587:role/pickle-brining-us-west-1-lambdaRole
    timeout: 10
    events:
      - http:
          path: /reward/{token}
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                count: false

  index-staking:
    handler: service/index/handler.handler
    role: arn:aws:iam::135612478587:role/pickle-brining-us-west-1-lambdaRole
    timeout: 300
    events:
      - schedule:
          name: ${self:service}-${self:custom.stage}-index-staking-scrv
          description: "index historical data for pickle rewards contract scrv token"
          rate: rate(5 mintues)
          input:
            contract: "0xd86f33388bf0bfdf0ccb1ecb4a48a1579504dc0a"
            createdBlock: 10987327
            asset: "scrv"
      - schedule:
          name: ${self:service}-${self:custom.stage}-index-staking-weth
          description: "index historical data for pickle rewards contract weth token"
          rate: rate(5 mintues)
          input:
            contract: "0xa17a8883da1abd57c690df9ebf58fc194edab66f"
            createdBlock: 11147661
            asset: "weth"

  index-curve-stable:
    handler: service/index/curve/stable/handler.handler
    role: arn:aws:iam::135612478587:role/pickle-brining-us-west-1-lambdaRole
    timeout: 300
    events:
      - schedule:
          name: ${self:service}-${self:custom.stage}-index-curve-3pool
          description: "index historical data for pickle curve 3pool jar"
          rate: rate(5 mintues)
          input:
            contract: "0x1bb74b5ddc1f4fc91d6f9e7906cf68bc93538e33"
            createdBlock: 11010885
            asset: "3poolcrv"
      - schedule:
          name: ${self:service}-${self:custom.stage}-index-curve-scrv
          description: "index historical data for pickle curve scrv jar"
          rate: rate(5 mintues)
          input:
            contract: "0x68d14d66b2b0d6e157c06dc8fefa3d8ba0e66a89"
            createdBlock: 10973000
            asset: "scrv"
      - schedule:
          name: ${self:service}-${self:custom.stage}-index-compound-cdai
          description: "index historical data for pickle curve cdai jar"
          rate: rate(5 mintues)
          input:
            contract: "0x6949bb624e8e8a90f87cd2058139fcd77d2f3f87"
            createdBlock: 11044218
            asset: "cdai"

  index-curve-btc:
    handler: service/index/curve/btc/handler.handler
    role: arn:aws:iam::135612478587:role/pickle-brining-us-west-1-lambdaRole
    timeout: 300
    events:
      - schedule:
          name: ${self:service}-${self:custom.stage}-index-curve-renbtc
          description: "index historical data for pickle curve renbtc jar"
          rate: rate(5 mintues)
          input:
            contract: "0x2e35392f4c36eba7ecafe4de34199b2373af22ec"
            createdBlock: 11010898
            asset: "renbtccrv"

  index-uniswap-pool:
    handler: service/index/uniswap/handler.handler
    role: arn:aws:iam::135612478587:role/pickle-brining-us-west-1-lambdaRole
    timeout: 300
    events:
      - schedule:
          name: ${self:service}-${self:custom.stage}-index-uniswap-wbtc-eth
          description: "index historical data for pickle uniswap wbtc-eth jar"
          rate: rate(5 mintues)
          input:
            contract: "0xc80090aa05374d336875907372ee4ee636cbc562"
            createdBlock: 11010902
            asset: "wbtc-eth"
      - schedule:
          name: ${self:service}-${self:custom.stage}-index-uniswap-usdc-eth
          description: "index historical data for pickle uniswap usdc-eth jar"
          rate: rate(5 mintues)
          input:
            contract: "0x53bf2e62fa20e2b4522f05de3597890ec1b352c6"
            createdBlock: 10960599
            asset: "usdc-eth"
      - schedule:
          name: ${self:service}-${self:custom.stage}-index-uniswap-usdt-eth
          description: "index historical data for pickle uniswap usdt-eth jar"
          rate: rate(5 mintues)
          input:
            contract: "0x09fc573c502037b149ba87782acc81cf093ec6ef"
            createdBlock: 10960612
            asset: "usdt-eth"
      - schedule:
          name: ${self:service}-${self:custom.stage}-index-uniswap-dai-eth
          description: "index historical data for pickle uniswap dai-eth jar"
          rate: rate(5 mintues)
          input:
            contract: "0xcffa068f1e44d98d3753966ebd58d4cfe3bb5162"
            createdBlock: 10960588
            asset: "dai-eth"

  index-legacy-jars:
    handler: service/index/legacy/handler.handler
    role: arn:aws:iam::135612478587:role/pickle-brining-us-west-1-lambdaRole
    timeout: 900
